### PR TITLE
web: Add PWA

### PR DESCRIPTION
**Pull request by Vadim-Karpenko**
In addition to [https://github.com/renpy/renpy/pull/4126](https://github.com/renpy/renpy/pull/4126), this code uses generated icons to bring Progressive Web Application into web builds of Ren'Py.

A few things left to do:
- Replace `Ren'Py Web Game` with the project name in the manifest.json during the build.
- In the `service-worker.js` file replace `renpy-web-game` in the `var cacheName = 'renpy-web-game';` line with the current project name (should be slugified) and added a timestamp at the end of it, so the cache can be cleared on every build for all users that already installed application. Example: `my-game-1670133520`

### CODE REVIEW

**Comment by qinlili23333** [comment]
A good start, and some more advices here:

#### In manifest...
1. There should also be maskable icons which have transparent background and large empty margin for mask, like Android's adaptive icon ( in fact currently only Chrome on Android use this property )
2. Add this part to prevent multi instances
`
"launch_handler": {
        "route_to": "existing-client",
        "navigate_existing_client": "always"
    }
`
3. There should be `orientation` property. Maybe put "landscape-primary" as default and automatically determine with project's resolution in building?
4. Add this part to make it looks like a real app without browser UI
`
"display": "standalone",
    "display_override": [
        "fullscreen",
        "minimal-ui"
    ]
`

#### In service worker...
1. We shouldn't cache too much files in installing, this will let the installing take too long time and may results double fetch for the same file sometimes. We should cache everything when it is first time requested, just request and cache it in fetch event handler. As core files must be loaded for the first time run, these files can be automatically cached. To fully implement this function, service worker should be installed at first and only if installation completed then do a refresh and start load game.
2. In game update, some resources haven't change. To save user's data we should migrate them from old cache to new cache. I recommend to make a hashlist of every file in each build, and make a file changelist after each build. When a new version of service worker is updated, in install handler should migrate files with no change to new cache. 


These advices are from my developing experience and here are two projects I made for reference.
1. https://github.com/GlacierLab/EverlastingSummerWasm
This project is a web portation of a CC-BY-SA RenPy game Everlasting Summer. U can reference the code in this project to see how to make a better user experience for PWA. (Sorry for Chinese only in the project. I'm not good at i18n so i cannot make multi language support.)
2. https://github.com/qinlili23333/545WebPlayer/blob/main/sw.js
A PWA music player project. Not RenPy, but has cache migration feature for unchanged resource. Only reference the code in the service worker. Cache migration code is the part wich has "AZUSA_PATCH".

**Comment by Vadim-Karpenko** [comment]
Thanks a lot for such an extensive reply from you! I have updated the manifest according to your advice. As for the service worker, it is good advice about cache invalidation and merging the existing cache with the new one, I'll try to implement your suggestion. For now, I've added a basic deletion of the old cached content but in a day or two will expand it into something more advanced.

**Comment by Vadim-Karpenko** [comment]
As for icons, it is already transparent (file that I added in this commit: [https://github.com/renpy/renpy-build/pull/51/commits/32a9f67d41c6043990717c516ba3c18ee3523bf3](https://github.com/renpy/renpy-build/pull/51/commits/32a9f67d41c6043990717c516ba3c18ee3523bf3)) so not sure if we need to update anything here.

**Comment by qinlili23333** [comment]
> As for icons, it is already transparent (file that I added in this commit: [32a9f67](https://github.com/renpy/renpy-build/commit/32a9f67d41c6043990717c516ba3c18ee3523bf3)) so not sure if we need to update anything here.

This page has a clear guidance for maskable icon.
https://web.dev/maskable-icon/
In short, maskable icons should have large margin for the mask.

**Comment by qinlili23333** [comment]
> Found time for it today, and I decided to use the content length (size of the file in bytes) from the headers instead of hashes. Not as perfect, but a lot easier to implement and should work just fine. I made some tests on my local machine, and it works great - once you change any file and version in `service-worker.js`, already installed apps make calls only for the content that changed, leaving everything else as is.

Use length is not a good choice because many CDN providers like Cloudflare automatically minify files when second time request from CDN. This may lead to changing of length, and resulting multi request for files that actually function the same.
This is why I suggest do the hash calc in exporting project as webpage. We only need to generate a list of unchanged files and fetch the list during update then migrate all these unchanged files to new cache if found in old cache. This means we only need to request changelist once in each version update, instead of tons of HEAD requests.

**Comment by Vadim-Karpenko** [comment]
> > Found time for it today, and I decided to use the content length (size of the file in bytes) from the headers instead of hashes. Not as perfect, but a lot easier to implement and should work just fine. I made some tests on my local machine, and it works great - once you change any file and version in `service-worker.js`, already installed apps make calls only for the content that changed, leaving everything else as is.
> 
> Use length is not a good choice because many CDN providers like Cloudflare automatically minify files when second time request from CDN. This may lead to changing of length, and resulting multi request for files that actually function the same. This is why I suggest do the hash calc in exporting project as webpage. We only need to generate a list of unchanged files and fetch the list during update then migrate all these unchanged files to new cache if found in old cache. This means we only need to request changelist once in each version update, instead of tons of HEAD requests.

The downside of hashes is if the user manually edits cached files (e.g adding Google Analytics into index.html) it will not be pushed into the new cache because the hash in the changelist will remain the same (the build version hasn't changed), and the developer won't even realize the issue, which will result in a lot of users see different versions of a webpage. We can't ask all devs to generate hashes manually every time they edit those files either, because most devs are not aware of such things as PWA, let alone generating hashes for its cache system. 

As for the HEAD requests, it is not that critical, even though there are a lot of them (one per each file we are caching), they are really small - 200-400 bytes each. So 8 files right now to cache, which results in 2.4kb of bandwidth on average, on top of that, it is only triggered once the version is changed, and not every time the page is loaded.

About Cloudflare and other CDNs, it is quite interesting, I didn't know there's a feature that will automatically minify your files. From what I understood, it does not minify them on the first request, right? It is a bit useless if so. I'm wondering if the last-modified header is being changed once the file is minified? I can't check it, but if not, we can use it to distinguish min version from the normal one and skip the update if the date is the same as your current cached file.

Also, maybe we should just minify all .js files during the build?

**Comment by qinlili23333** [comment]
> 

Users can also edit the file changelist. We can set a switch for users to choose whether enable the hash patch function, and default set to off.
HEAD requests are small yes, but do have network latency. In most browsers, connections to a single origin are limited, e.g. 6 connections one origin in Chrome. 
For Cloudflare, it returns origin file in first request and return minified file since second request, the date property in http head is also changed. U can test on my site with Cloudflare. Use this url ( https://545.qinlili.bid/lib/base64.js ), simply add some query (such as https://545.qinlili.bid/lib/base64.js?123123 ) to get origin file, then force refresh to get minified file.
Minify all files during build should be provided as a selectable function and default off. For users directly release their game this will help a lot. But some users also need to integrate their game to other projects. A switch for user to choose can solve this problem.

I wrote a service worker template based on my projects experiences.
```
var APP_PREFIX = '|GAME NAME|'
var VERSION = '|CURRENT VERSION|'
var VERSION_AZUSA_PATCH_USE = '|LAST VERSION|'
var AZUSA_PATCH_SKIP_LIST = [
    './Files_Without_Change',
    './This_Should_Generate_In_Build'
]
var CACHE_NAME = APP_PREFIX + VERSION;
var AZUSA_CACHE = APP_PREFIX + VERSION_AZUSA_PATCH_USE;
self.addEventListener('fetch', event => {
    if (event.request.url.indexOf("getVersionWorker") > 0) {
        event.respondWith(new Response(VERSION));
        return;
    }
    //Dont cache non-GET requests
    //Dont cache non-http requests for chrome extentions
    //Dont cache requests with ForceNoCache tag for special use
    //Dont cache requests from other origin
    if (event.request.method == "GET" && event.request.url.indexOf("http") == 0 && event.request.url.indexOf("ForceNoCache") == -1 && (new URL(event.request.url)).origin == location.origin) {
        event.respondWith(
            caches.open(CACHE_NAME).then(async cache => {
                return cache.match(event.request).then(response => {
                    return response || fetch(event.request).then(response => {
                        //Dont cache 400+ responses
                        if (response.status < 400) {
                            cache.put(event.request, response.clone());
                            console.log('file cached : ' + event.request.url)
                        }
                        return response;
                    }).catch(error => {
                        console.log("failed to fetch :" + event.request.url)
                        console.log(error);
                    });
                });
            })

        );
    } else {
        event.respondWith(fetch(event.request))
    }
});
self.addEventListener('install', e => {
    self.skipWaiting();
    const install = async () => {
        const cache = await caches.open(CACHE_NAME)
        console.log('installing cache : ' + CACHE_NAME)
        if ((await caches.has(AZUSA_CACHE))) {
            console.log("Found Old Cache! Azusa Patch Working...");
            caches.open(AZUSA_CACHE).then(oldCache => {
                AZUSA_PATCH_SKIP_LIST.forEach(async url => {
                    let tempResponse = await oldCache.match(url);
                    if (tempResponse) {
                        console.log("Azusa Success Transfer Old Cache : " + url)
                        cache.put(url, tempResponse);
                    }
                })
            })
        };
        return true;
    }
    e.waitUntil(install());
});
self.addEventListener('activate', e => {
    e.waitUntil(
        caches.keys().then((keyList) => {
            var cacheWhitelist = keyList.filter(key => {
                return key.indexOf(APP_PREFIX)
            })
            cacheWhitelist.push(CACHE_NAME);
            return Promise.all(keyList.map((key, i) => {
                if (cacheWhitelist.indexOf(key) === -1) {
                    console.log('deleting cache : ' + keyList[i])
                    return caches.delete(keyList[i])
                }
            }))
        })
    )
});
```

**Comment by qinlili23333** [comment]
Yes we cannot access the former build, but we can save each build's hash list in project's folder. Just in project folder save as `lastbuild.txt`. 
Users do forget to change something important, so a switch with default off can solve this. In default, cache migration is disabled, but user can manually enable it. Once the user recognize it needs to enable, he will also recognize he should maintance the changelist file.

For Cloudflare, in my personal test, seems every datacenter will minify seperately. For example, second request in HongKong will be minified content served from HKG server, but if then I request in Brisbane, BNE server will still return the origin one. And sometimes the server will clear cache for minified file. 

Cache everything from the same origin is nearly the best choice for my real test. Cache file is not just for quicker loading, but also for offline gaming. U can visit a real RenPy web game with everything cached on my site ( https://es.qinlili.bid ). (Sorry for only Chinese in game support, but just test the function is OK.) U can play anything loaded offline and I even plan to provide a "Cache Whole Game" option for users who want to preload all files to cache and run offline, such as for playing on the plane without network.
We can also provide a function for user to clear cache manually if they need.

**Comment by Vadim-Karpenko** [comment]
I think I've found a perfect solution - the ETag header, which is a hash of the file made by the server, and it is consistent with both minified and normal versions. Here's more information: [link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag). I made a commit, and I've even tested it locally, and it works great. Let me know what you think about this.
The only thing left is to decide whether should we cache all files or just the core ones. I've contacted @renpytom about this, let's hear an opinion from him or someone from the renpy team.

**Comment by Vadim-Karpenko** [comment]
upd to the previous comment, Tom said (in discord) that media content shouldn't be cached, only core files

**Comment by qinlili23333** [comment]
> I think I've found a perfect solution - the ETag header, which is a hash of the file made by the server, and it is consistent with both minified and normal versions. Here's more information: [link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag). I made a commit, and I've even tested it locally, and it works great. Let me know what you think about this. The only thing left is to decide whether should we cache all files or just the core ones. I've contacted @renpytom about this, let's hear his opinion or from someone from the renpy team.

ETag is a really good choice, if the server support it. Most CDN support it weil. I think maybe we can detect etag first, if no etag in header, then fallback to length, as local test server usually have no etag support. 

Maybe we can also setup a cache level option and in default only core files are cached. We can have these levels:
Level 0: nothing cached
Level 1(default): core files cached
Level 2: frequent use media files cached
Level 3: everything cached

And also a precache option, if set to on, cache file during install, otherwise only cache file when the file is first time requested.

**Review by qinlili23333 — APPROVED** [review]

**Comment by qinlili23333** [comment]
yes we can do advanced cache function in further new pr, not only cache levels and we can do more.

**Pull request merged**
